# Site settings
title: "Planet Rock 2"
email: kongohgames@gmail.com
topheading:"KongOh Presents:"
banner: "images/banner.jpg"
heading1: "A COSMIC ADVENTURE THROUGH"
heading2: "SPACE AND SOUND."

description1: "Planet Rock 2: Electric Boogaloo is a journey through sound and space. Travel through a surreal galaxy, colliding with interstellar sounds to create beautiful music. Wake up and return to a dark and chaotic reality and witness the transformation."
description2: "The game is developed by KongOh Games (Kenny Kong and Peter Oh). The game's soundtrack features the freshest galactic funk, soul, and hip-hop from acclaimed musical artists Zion I and DJ Fleg."

baseurl: ""
url: "http://planetrock.kongohgames.com"
facebook_username: "kongohgames"
twitter_username: kongohgames
github_username:  kongoh

# Build settings
markdown: kramdown
permalink: pretty
